CREATE TABLE IF NOT EXISTS film (
    id BIGSERIAL PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    durasi_menit INT NOT NULL,
    deskripsi TEXT,
    rating_usia VARCHAR(10) NOT NULL DEFAULT 'SU',
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    dibuat_pada TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    diperbarui_pada TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
