CREATE TABLE IF NOT EXISTS jadwal (
    id BIGSERIAL PRIMARY KEY,
    film_id BIGINT NOT NULL REFERENCES film(id) ON DELETE RESTRICT,
    studio_id BIGINT NOT NULL REFERENCES studio(id) ON DELETE RESTRICT,
    waktu_mulai TIMESTAMP WITH TIME ZONE NOT NULL,
    waktu_selesai TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',
    dibuat_pada TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    diperbarui_pada TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_jadwal_film_mulai ON jadwal(film_id, waktu_mulai);
CREATE INDEX IF NOT EXISTS idx_jadwal_studio_mulai ON jadwal(studio_id, waktu_mulai);
