CREATE TABLE IF NOT EXISTS studio (
    id BIGSERIAL PRIMARY KEY,
    bioskop_id BIGINT NOT NULL REFERENCES bioskop(id) ON DELETE CASCADE,
    nama VARCHAR(100) NOT NULL,
    kapasitas INT NOT NULL DEFAULT 0,
    tipe VARCHAR(50) NOT NULL DEFAULT 'REGULAR',
    dibuat_pada TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    diperbarui_pada TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_studio_bioskop_id ON studio(bioskop_id);
