CREATE TABLE IF NOT EXISTS pesanan (
    id BIGSERIAL PRIMARY KEY,
    pengguna_id BIGINT NOT NULL REFERENCES pengguna(id) ON DELETE RESTRICT,
    nomor_pesanan VARCHAR(100) NOT NULL UNIQUE,
    total_harga NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    kedaluwarsa_pada TIMESTAMP WITH TIME ZONE,
    dibuat_pada TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    diperbarui_pada TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pesanan_pengguna ON pesanan(pengguna_id);
CREATE INDEX IF NOT EXISTS idx_pesanan_status ON pesanan(status);
